### ISSUE TITLE
Update overall design to match current ACM Styleguide

### ISSUE THREAD

**Issue by jodymlin** [uclaacm/hoth.uclaacm.com#114]
We need to change the general design of the website to comply with [ACM Styleguide](https://design.uclaacm.com/).

### Typography
*Headers*: Poppins
*Body*: Open Sans

More in depth on typography styles can be found under the Typography section [here](https://design.uclaacm.com/guidelines/).

### Colors
The list of colors can be found [here](https://design.uclaacm.com/committees/hack/). 

(Not sure if this fell under #58, so adding it as a separate issue)

**Comment by TimothyGu** [comment]
Also change to new Hack logo. Check https://github.com/uclaacm/hack.uclaacm.com.

**Comment by curesh** [comment]
Change the last pair in the layouts file from "1,400" to "1,700".
