### ISSUE TITLE
Create FAQ section

### ISSUE THREAD

**Issue by jamieliu386** [uclaacm/hoth.uclaacm.com#13]
Create FAQ section as shown in the [figma](https://www.figma.com/file/sC4tsO37gn2qgn1ol1yfZq/HOTH-Website?node-id=15%3A9)

**Comment by TimothyGu** [comment]
We still need to tweak the styling after #18.

**Comment by jamieliu386** [comment]
Discovered an issue where, when viewing from an iPhone 5/SE, there is a visual glitch when opening/closing questions that span multiple lines.
