### ISSUE TITLE
Add information links to Workshop Page

### ISSUE THREAD

**Issue by jodymlin** [uclaacm/hoth.uclaacm.com#164]
Each of our workshops on the workshop page currently includes the embedded youtube video, a title, description, and another link to the youtube video. 

Links to add to each workshop component
* link to the readme
* link to the slides

**Comment by S0han** [comment]
so right now you guys have the "see video" button that links to youtube

for the 2 link you want mentioned below do you also want to use a button like the "see video" button that links to readme/slides?

**Comment by jodymlin** [comment]
Hey @S0han! This website is currently an internal project within our organization and are not looking to collaborate with anyone outside our current team.

Thanks for checking out our website though 😃
