### ISSUE TITLE
Add Announcements page

### ISSUE THREAD

**Issue by jodymlin** [uclaacm/hoth.uclaacm.com#165]
Create a new page that contains any announcements for/during HOTH.

Rather than having announcements created by directly editing the a file in the repo, making a PR, and merging, we are thinking of using something similar to the [serverless comment system](https://www.gatsbyjs.com/blog/2018-04-10-how-to-handle-comments-in-gatsby-blogs/) Gatsby recommends.

**Comment by khxia** [comment]
Use a Github Action. 
Triggered on the issue_comment event: 
https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#issue_comment 

Payload example:
https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#issue_comment 

make sure to filter to allow only team/organization

Run a script that calls the Github Issue API - list comment issues: https://docs.github.com/en/rest/reference/issues#list-issue-comments 
to get all comments and then inject into file

**Comment by jodymlin** [comment]
Let's break the PR's for this into smaller tasks so each person can take on a small piece

- [ ] Create static Announcements page
- [ ] Create an announcement component and list on page
- [ ] Create script to call Github Issue API to get all comments on an issue
- [ ] Create Github Action workflow that triggers on the issue_comment event
