### ISSUE TITLE
Use Netlify for PR preview

### ISSUE THREAD

**Issue by TimothyGu** [uclaacm/hoth.uclaacm.com#19]
@jamieliu386 has had good experience with Netlify with Teach LA. It provides useful features like pull request preview, which is something that would be cool to have. It also allows deployment, which may eventually obsolete #16.

We should aim to create a [open source plan](https://www.netlify.com/legal/open-source-policy/). There are a few things we have to do:

- [x] Adopt code of conduct. I recommend adopting [Contributor Covenant](https://www.contributor-covenant.org/), one of the most widely used CoCs.
- [x] Add a badge to our README, perhaps after we get approved.

These are not technically needed, but I think we should also do this to increase the chances of approval:

- [x] Write an actual README for what this repo is about. This way we will make our repo much better than hack.uclaacm.com's haha.
- [x] Update https://github.com/uclaacm/hoth.uclaacm.com/blob/c330bef69ec443e152aafa07b31d78d6771fa6d0/LICENSE#L3 to say our names instead.

----

If signing up for an open source plan somehow falls through, we could probably sign our @uclaacmhack GitHub account up for Netlify and use an individual plan. That’s bad though, and I hope we won’t have to do that.

**Comment by jamieliu386** [comment]
Submitted application for Netlify's open source plan, currently awaiting response.

**Comment by jamieliu386** [comment]
Received a response from someone on the Netlify team:

> Looks good to me!  Could you please go ahead and add that link to our service on your main page and drop me a link to show me it's done? Then I'll create you a sponsored team :)

**Comment by jamieliu386** [comment]
Got approved for a sponsored team :)
