### ISSUE TITLE
Fix `alignItems` prop value in Banner

### ISSUE THREAD

**Issue by jodymlin** [uclaacm/hoth.uclaacm.com#223]
There are some console errors because invalid values are passed in

**Comment by katelynsyu** [comment]
the console issues are
- invalid prop value of left passed into justify in banner.js inside of a Grid component
- invalid prop value of left passed into alignItems in banner.js inside of a Grid component
- The prop `children` is marked as required in `ForwardRef(Container)`, but its value is `null`.
- The prop `to` is marked as required in `GatsbyLink`, but its value is `undefined`.
