### ISSUE TITLE
Sticky headers on Schedule page

### ISSUE THREAD

**Issue by nareha** [uclaacm/hoth.uclaacm.com#226]
Currently, the headings for each of the time segments of the schedule page are sticky to their sections, but there's an awkward gap between the top of the page and the actual sticky header.

![the issue with sticky header offset](https://user-images.githubusercontent.com/53708656/154618475-7cd30b89-079e-4057-840b-77116b1d412e.png)

Two possible solutions:
- Make headers non-sticky
- Fix header to stick to the top or add background to that blank space (unsure of this implementation)

I don't think the sticky header design is crucial so this is probably a design choice you can make.

**Comment by khxia** [comment]
It used to be sticky by intentional, but the background bug wasn't there.
https://deploy-preview-150--acm-hoth.netlify.app/schedule

**Comment by nareha** [comment]
Would it be possible to add a bit of padding to the heading seen in the preview? If that's not too much work, it would look nice
