### ISSUE TITLE
Inconsistent header styling across pages

### ISSUE THREAD

**Issue by katelynsyu** [uclaacm/hoth.uclaacm.com#247]
- The workshop page's header title thing is a larger font than the rest of the pages....
- Pretty sure padding isn't the same across the different pages when the window changes sizes. By this I mean that the prizes page uses breakpoints so that if the window size changes, the padding above the title goes from theme.spacing(11) to theme.spacing(4). Other pages like the schedule just have paddingTop hardcoded as theme.spacing(11). as a result...
<img width="678" alt="Screen Shot 2022-02-23 at 5 14 27 PM" src="https://user-images.githubusercontent.com/41168140/155438365-edd9de7a-f803-4178-b192-b74f6f14d507.png">
<img width="678" alt="Screen Shot 2022-02-23 at 5 14 38 PM" src="https://user-images.githubusercontent.com/41168140/155438401-35920565-1c59-4aba-b780-6cd7430b55e7.png">

**Comment by khxia** [comment]
Let's change the other pages to use the breakpoints as well.
