### ISSUE TITLE
Fix the pull request labeler

### ISSUE THREAD

**Issue by khxia** [uclaacm/hoth.uclaacm.com#285]
It's failing the check for all dependabot PRs

**Comment by maggieelli** [comment]
From this [article](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/), we see that Dependabot PR's are treated as forks with read-only permissions, so "any workflows that attempt to write to the repository to fail," including the labeler. To fix this, we just added the permissions mentioned in [this](https://github.com/actions/labeler/issues/12#issuecomment-1095272652) comment on another issue.
