### ISSUE TITLE
Update info

### ISSUE THREAD

**Issue by jakobreinwald** [uclaacm/hoth.uclaacm.com#296]
Update all of the logistical hackathon information (except for FAQ section) on the site for HOTH X:

- [x] HOTH 9 --> HOTH X
- [x] date and time (TBD)
- [x] location (TBD)

**Comment by SubramaniamSatyen** [comment]
Merged to main on 1/22 with changeset f20152aa9d7e6309d8826b4010adfd4a238a5ea1
