### ISSUE TITLE
Change the default Git branch name to "main"

### ISSUE THREAD

**Issue by TimothyGu** [uclaacm/hoth.uclaacm.com#36]
Git's use of the term "master" is problematic; see https://mail.gnome.org/archives/desktop-devel-list/2019-May/msg00066.html. While GitHub has [plans](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/) to make this change easier on each repo, we should just do it now.

Assigning to @jamieliu386 as she has experience doing this for other repos.

**Comment by jamieliu386** [comment]
Made transition from "master" to "main"

Steps:
``` shell
git checkout master                    # switch to master branch
git pull                               # pull changes
git checkout -b main                   # create new main branch off of master
git push --set-upstream origin main    # push main branch to remote
git branch -d master                   # delete master branch locally

```

- edit base of current PRs to main
- edit repository's base branch to main
- edit netlify production branch to main

``` shell
git push origin --delete master    # push master branch deletion to remote
git remote prune origin            # prune origin
```

To update your local clone:
``` shell
git checkout master
# go to master branch
git branch -m master main
# rename local master branch to main
git fetch
# fetch latest commits
git branch --unset-upstream
# remove link to origin/master
git branch -u origin/main
# add link to origin/main
git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main
# update default branch to origin/main
```

**Comment by TimothyGu** [comment]
Deployment seems to be working: ![Screenshot from Netlify saying: "Production: main (published)"](https://user-images.githubusercontent.com/1538624/85209338-1498fb80-b305-11ea-979b-5b3890cb79ed.png). Yay!
