### ISSUE TITLE
Update contributor list on README

### ISSUE THREAD

**Issue by jakobreinwald** [uclaacm/hoth.uclaacm.com#380]
Move inactive contributors to Past Contributors and add new contributors(interns) to current ACM Hack's Dev Team list.

**Comment by SPerrott22** [comment]
Hi @jakobreinwald, just curious, are all the previous contributors going to moved to past contributors or do we keep current ACM officers e.g. this is what I've done currently
<img width="603" alt="image" src="https://github.com/uclaacm/hoth.uclaacm.com/assets/56176775/adb940f8-7076-4c9b-a108-9c0392c4f918">

**Comment by maggieelli** [comment]
Closed by #398
