### ISSUE TITLE
Homepage countdown may be clipped on mobile

### ISSUE THREAD

**Issue by Timthetic** [uclaacm/hoth.uclaacm.com#46]
<img width="380" alt="Screen Shot 2020-06-23 at 12 56 04 AM" src="https://user-images.githubusercontent.com/33593205/85376336-68196e00-b4ec-11ea-8b14-b14f245d20b0.png">
When the screen gets small enough, the countdown on the homepage exits the screen. Above is the homepage for the dimensions of "iPhone 6/7/8 plus"

**Comment by jamieliu386** [comment]
Looks like the "Hack on the Hill 7" alignment is also off for small screens.

Thanks for catching this!
