### ISSUE TITLE
Polish the design

### ISSUE THREAD

**Issue by TimothyGu** [uclaacm/hoth.uclaacm.com#58]
The home page design could be polished a bit. We should reach out to @uclaacm/design.

**Comment by Kimeiga** [comment]
I would start by replacing the gatsby favicon haha
![image](https://user-images.githubusercontent.com/20587215/86539962-cd3e6d80-beb5-11ea-8bc0-ed70147d7ca5.png)

I see yall are using material ui! I saw that they released their library for Sketch, but unfortunately we don't have Sketch
https://twitter.com/MaterialUI/status/1244519729978437633

We can just try doing a mockup of what the home page could look like instead, but it might not have the exact assets. Feel free to submit a design request through trello!

**Comment by TimothyGu** [comment]
Ha, this ticket was really just a reminder for us to contact y'all. Thanks for popping by!

The favicon issue is #39; we are on it.

Quite frankly, a mock-up for the home page is more than sufficient.

**Comment by jamieliu386** [comment]
Submitted a [ticket](https://trello.com/c/WzCC5TPW/206-product-hoth-website-design-advice) on the ACM Design Trello.
