### ISSUE TITLE
New Gallery page design

### ISSUE THREAD

**Issue by TimothyGu** [uclaacm/hoth.uclaacm.com#79]
Redesign the gallery page as per Design's feedback

https://www.figma.com/file/sC4tsO37gn2qgn1ol1yfZq/HOTH-Website?node-id=15%3A11

**Comment by jamieliu386** [comment]
I'm pretty sure this will be resolved with the redesign of the gallery page, so I think we should have an overarching issue for the design of that page and delete this one.

**Comment by TimothyGu** [comment]
Carousel: put it at the top of the page; i.e., status quo.
