### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by jamieliu386** [uclaacm/hoth.uclaacm.com#99]
![image](https://user-images.githubusercontent.com/35614552/104113578-ff97b000-52c8-11eb-823b-e1a1077314db.png)
Information is out of date.

**Comment by akanksha26281** [comment]
Can I work on this issue?

**Comment by jamieliu386** [comment]
See updated FAQ questions here: https://docs.google.com/document/d/1O4g6-YIwxLZeKxcdWtMk9gGDw1gY1nUcQs8GUTtutC4/edit
